name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Stockpile scheme using iPhone simulator
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Default Scheme to Stockpile
        run: |
          defaultScheme="Stockpile"
          echo Using default scheme: $defaultScheme
      - name: Build
        env:
          scheme: ${{ env.defaultScheme }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=iPhone 13"
